# .github/settings.yml
# Probot Settings config for org-wide label synchronization
# This will automatically apply these labels to all repos where the app is installed.

repository:
  has_issues: true
  has_projects: true
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  # 🧭 Issue Types
  - name: "type:feature"
    color: "1F883D"
    description: "A new feature or enhancement."
  - name: "type:bug"
    color: "D73A4A"
    description: "An error, failure, or unexpected behavior."
  - name: "type:chore"
    color: "C5DEF5"
    description: "Maintenance, refactors, or internal improvements."
  - name: "type:docs"
    color: "0366D6"
    description: "Documentation-related updates or fixes."
  - name: "type:design"
    color: "FBCA04"
    description: "UI/UX design work, prototypes, or visual assets."

  # ⚡ Priority
  - name: "priority:P0-critical"
    color: "000000"
    description: "Highest priority. Must fix or implement immediately."
  - name: "priority:P1-high"
    color: "B60205"
    description: "High impact or blocking work."
  - name: "priority:P2-medium"
    color: "D93F0B"
    description: "Normal priority, scheduled for upcoming sprint."
  - name: "priority:P3-low"
    color: "FBCA04"
    description: "Low urgency or nice-to-have improvement."

  # 🧩 Platform / Area
  - name: "platform:web"
    color: "0E8A16"
    description: "Work specific to the web app."
  - name: "platform:ios"
    color: "1D76DB"
    description: "Work specific to the iOS app."
  - name: "platform:android"
    color: "A97BFF"
    description: "Work specific to the Android app."
  - name: "platform:backend"
    color: "5319E7"
    description: "Server, API, or database-related work."
  - name: "platform:infra"
    color: "0052CC"
    description: "DevOps, CI/CD, or infrastructure changes."

  # 🚦 Status
  - name: "status:in-progress"
    color: "FBCA04"
    description: "Currently being worked on."
  - name: "status:blocked"
    color: "D93F0B"
    description: "Waiting on dependencies or external input."
  - name: "status:needs-review"
    color: "0E8A16"
    description: "Awaiting peer or code review."
  - name: "status:ready"
    color: "5319E7"
    description: "Ready for testing, deployment, or QA."
  - name: "status:done"
    color: "BFD4F2"
    description: "Completed or merged."

  # 🧹 Maintenance
  - name: "maintenance:dependencies"
    color: "E99695"
    description: "Dependency or version updates."
  - name: "maintenance:security"
    color: "E11D21"
    description: "Security-related updates or fixes."
  - name: "maintenance:ci-cd"
    color: "BFDADC"
    description: "Build, workflow, or automation updates."
  - name: "maintenance:cleanup"
    color: "C2E0C6"
    description: "Code cleanup, formatting, or reorganization."
  - name: "maintenance:research"
    color: "C5DEF5"
    description: "Exploration, proof of concept, or investigation."

  # 💬 Meta
  - name: "discussion"
    color: "F9D0C4"
    description: "Brainstorming or conceptual conversation."
  - name: "good first issue"
    color: "7057FF"
    description: "Beginner-friendly issue for onboarding contributors."
  - name: "help wanted"
    color: "008672"
    description: "Contributors are welcome to help."

# Optional: default branch protection rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: false
      required_status_checks:
        strict: true
        contexts: []
      restrictions: null
